name: Node.js CI

on:
  push:
    branches: [ main ]
permissions:
    contents: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set Base Path
        run: echo "NEXT_PUBLIC_BASE_PATH=/$GITHUB_REPOSITORY" >> $GITHUB_ENV  
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: npm

      - name: Build
        run: |
          npm ci
          npm run build
          touch out/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
            branch: gh-pages
            folder: out
